# Generated by Django 5.0.7 on 2025-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('new_gift', 'New Gift Matching Search'), ('new_review', 'New Review')], max_length=50),
        ),
    ]
