# Generated by Django 5.0.7 on 2024-07-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0001_initial'),
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='hobbies.hobby'),
        ),
    ]
