# Generated by Django 5.0.7 on 2024-08-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftcategory',
            options={'verbose_name_plural': 'gift categories'},
        ),
    ]
