# Generated by Django 5.0.7 on 2024-12-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_alter_giftcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='suitable_age_range',
            field=models.CharField(blank=True, choices=[('0-12', 'Bambini (0-12)'), ('13-17', 'Adolescenti (13-17)'), ('18-24', 'Giovani Adulti (18-24)'), ('25-34', 'Adulti (25-34)'), ('35-50', 'Adulti (35-50)'), ('50+', 'Senior (50+)')], max_length=10),
        ),
        migrations.AddField(
            model_name='gift',
            name='suitable_gender',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('O', 'Altro'), ('U', 'Unisex')], max_length=1),
        ),
        migrations.AddField(
            model_name='gift',
            name='suitable_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
