# Generated by Django 5.0.7 on 2025-01-25 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0007_gift_average_rating_review_reviewimage_reviewvote'),
        ('hobbies', '0004_alter_hobby_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unisex')], max_length=1)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('order_by', models.CharField(choices=[('-average_rating', 'Highest Rating'), ('average_rating', 'Lowest Rating'), ('priceMin', 'Lowest Price'), ('priceMax', 'Highest Price'), ('name', 'Name A-Z'), ('-name', 'Name Z-A')], default='-average_rating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to='gifts.giftcategory')),
                ('hobbies', models.ManyToManyField(blank=True, related_name='saved_searches', to='hobbies.hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
