# Generated by Django 5.0.7 on 2024-12-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_category_options_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
