# Generated by Django 5.0.7 on 2024-08-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHobbies',
        ),
    ]
